//! Auto-generated wrapper for user ODE.
//! This file is generated by the Python build system - do not edit manually.
//!
//! It imports the user's ODE definition and exports C ABI functions
//! that the solver can call.

const user = @import("{user_ode_path}");

// ============================================================
// C ABI Exports
// ============================================================

/// Wrapper that converts C ABI to clean Zig signature.
export fn ode_func(
    t: f64,
    y: [*]const f64,
    dydt: [*]f64,
    params_ptr: ?*const anyopaque,
    dim: usize,
) callconv(.c) void {{
    _ = dim;
    const params: *const user.Params = @ptrCast(@alignCast(params_ptr.?));
    user.ode(t, y[0..user.DIM], dydt[0..user.DIM], params);
}}

/// Returns the dimension of the state space.
export fn ode_dim() callconv(.c) usize {{
    return user.DIM;
}}

/// Returns the size of the Params struct in bytes.
export fn ode_param_size() callconv(.c) usize {{
    return @sizeOf(user.Params);
}}
