"""Generate self-consistent ground truth data for integration tests.

Runs all integration test systems with seed=42 and CPU solver to produce
regression-test ground truth generated by pybasin itself.

Usage:
    uv run python -m scripts.generate_ground_truths
"""

import json
from collections import Counter
from collections.abc import Callable
from pathlib import Path

import pandas as pd

from case_studies.duffing_oscillator.setup_duffing_oscillator_system import (
    setup_duffing_oscillator_system,
)
from case_studies.friction.main_friction_v_study import FRICTION_V_D_VALUES
from case_studies.friction.setup_friction_system import setup_friction_system
from case_studies.lorenz.main_lorenz_hyperpN import LORENZ_HYPERPARAMETER_N_VALUES
from case_studies.lorenz.main_lorenz_hyperpTol import LORENZ_RTOL_VALUES
from case_studies.lorenz.main_lorenz_sigma import LORENZ_SIGMA_VALUES
from case_studies.lorenz.setup_lorenz_system import setup_lorenz_system
from case_studies.pendulum.main_pendulum_case2 import CASE2_T_VALUES
from case_studies.pendulum.main_pendulum_hyperparameters import HYPERPARAMETER_N_VALUES
from case_studies.pendulum.setup_pendulum_system import setup_pendulum_system
from pybasin.basin_stability_estimator import BasinStabilityEstimator
from pybasin.basin_stability_study import BasinStabilityStudy
from pybasin.protocols import SolverProtocol
from pybasin.study_params import SweepStudyParams
from pybasin.types import SetupProperties, StudyResult
from pybasin.utils import set_seed

_INTEGRATION_DIR = Path(__file__).parent.parent / "tests" / "integration"
_PENDULUM_GT_DIR = _INTEGRATION_DIR / "pendulum"
_DUFFING_GT_DIR = _INTEGRATION_DIR / "duffing"
_FRICTION_GT_DIR = _INTEGRATION_DIR / "friction"
_LORENZ_GT_DIR = _INTEGRATION_DIR / "lorenz"

_PENDULUM_LABELS: list[str] = ["FP", "LC", "NaN"]
_DUFFING_JSON_LABELS: list[str] = ["y1", "y2", "y3", "y4", "y5", "NaN"]
_DUFFING_JSON_TO_PYTHON_LABEL: dict[str, str] = {
    "y1": "$\\bar{y}_1$",
    "y2": "$\\bar{y}_2$",
    "y3": "$\\bar{y}_3$",
    "y4": "$\\bar{y}_4$",
    "y5": "$\\bar{y}_5$",
    "NaN": "NaN",
}
_LORENZ_JSON_LABELS: list[str] = ["butterfly1", "butterfly2", "unbounded", "NaN"]
_LORENZ_JSON_TO_PYTHON_LABEL: dict[str, str] = {
    "butterfly1": "chaotic attractor 1",
    "butterfly2": "chaotic attractor 2",
    "unbounded": "unbounded",
    "NaN": "NaN",
}


def _force_cpu(props: SetupProperties) -> tuple[SolverProtocol | None, SetupProperties]:
    """Extract a CPU-forced solver from props and force sampler to CPU in place.

    :param props: Setup properties from a case study setup function.
    :return: Tuple of (cpu_solver_or_none, props_with_cpu_sampler).
    """
    solver = props.get("solver")
    cpu_solver = solver.clone(device="cpu") if solver is not None else None

    sampler = props["sampler"]
    sampler.min_limits = sampler.min_limits.cpu()
    sampler.max_limits = sampler.max_limits.cpu()
    sampler.device = sampler.min_limits.device

    return cpu_solver, props  # type: ignore[return-value]


def _run_bse(
    props: SetupProperties, solver: SolverProtocol | None, n: int
) -> tuple[BasinStabilityEstimator, StudyResult]:
    feature_extractor = props.get("feature_extractor")
    estimator = props.get("estimator")

    if solver is None:
        raise ValueError("Baseline ground truth generation requires a solver")
    if feature_extractor is None:
        raise ValueError("Baseline ground truth generation requires a feature extractor")
    if estimator is None:
        raise ValueError("Baseline ground truth generation requires an estimator")

    bse = BasinStabilityEstimator(
        n=n,
        ode_system=props["ode_system"],
        sampler=props["sampler"],
        solver=solver,
        feature_extractor=feature_extractor,
        predictor=estimator,
        template_integrator=props.get("template_integrator"),
        feature_selector=None,
    )
    result = bse.run()
    return bse, result


def _save_point_csv(bse: BasinStabilityEstimator, csv_path: Path) -> None:
    assert bse.y0 is not None
    assert bse.solution is not None and bse.solution.labels is not None

    y0 = bse.y0.cpu().numpy()
    labels: list[str] = [str(lbl) for lbl in bse.solution.labels]

    point_columns: dict[str, object] = {f"x{i + 1}": y0[:, i] for i in range(y0.shape[1])}
    point_columns["label"] = labels

    df = pd.DataFrame(point_columns)
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(csv_path, index=False)


def _build_baseline_json(
    result: StudyResult,
    n: int,
    json_labels: list[str],
    json_to_python_label: dict[str, str],
) -> list[dict[str, object]]:
    labels_arr = result["labels"]
    assert labels_arr is not None

    counts_python: Counter[str] = Counter(str(lbl) for lbl in labels_arr)
    errors = result["errors"]
    data: list[dict[str, object]] = []

    for json_label in json_labels:
        python_label = json_to_python_label.get(json_label, json_label)
        count = counts_python.get(python_label, 0)
        bs = count / n
        se = errors[python_label]["e_abs"] if count > 0 and python_label in errors else 0.0
        data.append(
            {
                "label": json_label,
                "basinStability": bs,
                "absNumMembers": count,
                "standardError": se,
            }
        )

    return data


def _build_sweep_json_point(
    result: StudyResult,
    parameter: float | int,
    json_labels: list[str],
    json_to_python_label: dict[str, str],
) -> dict[str, object]:
    bs = result["basin_stability"]
    errors = result["errors"]

    point: dict[str, object] = {"parameter": parameter}
    for json_label in json_labels:
        python_label = json_to_python_label.get(json_label, json_label)
        point[f"bs_{json_label}"] = bs.get(python_label, 0.0)
        point[f"err_{json_label}"] = (
            errors[python_label]["e_abs"] if python_label in errors else 0.0
        )

    return point


def _write_json(json_path: Path, payload: dict[str, object]) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    with open(json_path, "w") as f:
        json.dump(payload, f, indent=4)


def _export_baseline_ground_truth(
    setup_function: Callable[[], SetupProperties],
    n: int,
    csv_path: Path,
    json_path: Path,
    json_labels: list[str],
    json_to_python_label: dict[str, str],
    print_name: str,
    system_name: str = "",
    case_name: str = "",
) -> None:
    set_seed(42)
    props = setup_function()
    solver, props = _force_cpu(props)

    bse, result = _run_bse(props, solver, n)
    _save_point_csv(bse, csv_path)

    json_data = _build_baseline_json(result, n, json_labels, json_to_python_label)
    label_map = {k: v for k, v in json_to_python_label.items() if k != v}
    _write_json(
        json_path,
        {
            "system_name": system_name,
            "case_name": case_name,
            "label_map": label_map,
            "data": json_data,
        },
    )

    print(f"{print_name} baseline done: n={n}, BS={result['basin_stability']}")


def _export_sweep_ground_truth(
    setup_function: Callable[[], SetupProperties],
    parameter_name: str,
    parameter_values: list[float] | list[int],
    n: int | None,
    csv_dir: Path,
    json_path: Path,
    json_labels: list[str],
    json_to_python_label: dict[str, str],
    print_name: str,
    system_name: str = "",
    case_name: str = "",
) -> None:
    set_seed(42)
    props = setup_function()
    solver, props = _force_cpu(props)
    feature_extractor = props.get("feature_extractor")
    estimator = props.get("estimator")
    template_integrator = props.get("template_integrator")
    effective_n: int = n if n is not None else props["n"]

    if solver is None:
        raise ValueError(f"{print_name} requires a solver")
    if feature_extractor is None:
        raise ValueError(f"{print_name} requires a feature extractor")
    if estimator is None:
        raise ValueError(f"{print_name} requires an estimator")

    study_params = SweepStudyParams(**{parameter_name: list(parameter_values)})

    bss = BasinStabilityStudy(
        n=effective_n,
        ode_system=props["ode_system"],
        sampler=props["sampler"],
        solver=solver,
        feature_extractor=feature_extractor,
        estimator=estimator,
        study_params=study_params,
        template_integrator=template_integrator,
        compute_orbit_data=False,
        output_dir=None,
        verbose=False,
    )
    results = bss.run()

    csv_dir.mkdir(parents=True, exist_ok=True)
    json_data: list[dict[str, object]] = []
    index_rows: list[dict[str, object]] = []

    for i, (parameter, result) in enumerate(zip(parameter_values, results, strict=True)):
        csv_filename = f"param_{i + 1:03d}.csv"
        assert result["initial_condition"] is not None
        y0 = result["initial_condition"]
        labels = result["labels"]
        assert labels is not None
        label_strs: list[str] = [str(lbl) for lbl in labels]

        point_columns: dict[str, object] = {f"x{j + 1}": y0[:, j] for j in range(y0.shape[1])}
        point_columns["label"] = label_strs

        df = pd.DataFrame(point_columns)
        df.to_csv(csv_dir / csv_filename, index=False)

        json_data.append(
            _build_sweep_json_point(
                result,
                float(parameter) if isinstance(parameter, float) else int(parameter),
                json_labels,
                json_to_python_label,
            )
        )
        index_rows.append({"parameter_value": parameter, "filename": csv_filename})
        print(f"  {print_name} {parameter_name}={parameter}: {result['basin_stability']}")

    pd.DataFrame(index_rows).to_csv(csv_dir / "parameter_index.csv", index=False)
    label_map = {k: v for k, v in json_to_python_label.items() if k != v}
    _write_json(
        json_path,
        {
            "system_name": system_name,
            "case_name": case_name,
            "label_map": label_map,
            "data": json_data,
        },
    )
    print(f"{print_name} {parameter_name} done: {len(parameter_values)} points")


def generate_case1(n: int = 4000) -> None:
    """Generate baseline ground truth for pendulum case1 (n=4000, seed=42, CPU)."""
    _export_baseline_ground_truth(
        setup_function=setup_pendulum_system,
        n=n,
        csv_path=_PENDULUM_GT_DIR / "ground_truths" / "case1" / "main_pendulum_case1.csv",
        json_path=_PENDULUM_GT_DIR / "main_pendulum_case1.json",
        json_labels=_PENDULUM_LABELS,
        json_to_python_label={label: label for label in _PENDULUM_LABELS},
        print_name="pendulum case1",
        system_name="pendulum",
        case_name="case1",
    )


def generate_case2(n: int = 2000) -> None:
    """Generate parameter sweep ground truth for pendulum case2 (T sweep, n=2000/point)."""
    _export_sweep_ground_truth(
        setup_function=setup_pendulum_system,
        parameter_name='ode_system.params["T"]',
        parameter_values=CASE2_T_VALUES,
        n=n,
        csv_dir=_PENDULUM_GT_DIR / "ground_truths" / "case2",
        json_path=_PENDULUM_GT_DIR / "main_pendulum_case2.json",
        json_labels=_PENDULUM_LABELS,
        json_to_python_label={label: label for label in _PENDULUM_LABELS},
        print_name="pendulum case2",
        system_name="pendulum",
        case_name="case2",
    )


def generate_hyperparameters() -> None:
    """Generate N-sweep ground truth for pendulum hyperparameters study."""
    _export_sweep_ground_truth(
        setup_function=setup_pendulum_system,
        parameter_name="n",
        parameter_values=HYPERPARAMETER_N_VALUES,
        n=None,
        csv_dir=_PENDULUM_GT_DIR / "ground_truths" / "hyperparameters",
        json_path=_PENDULUM_GT_DIR / "main_pendulum_hyperparameters.json",
        json_labels=_PENDULUM_LABELS,
        json_to_python_label={label: label for label in _PENDULUM_LABELS},
        print_name="pendulum hyperparameters",
        system_name="pendulum",
        case_name="case3",
    )


def generate_duffing_baselines(n: int = 4000) -> None:
    """Generate baseline ground truth for Duffing supervised/unsupervised tests."""
    _export_baseline_ground_truth(
        setup_function=setup_duffing_oscillator_system,
        n=n,
        csv_path=_DUFFING_GT_DIR / "ground_truths" / "main" / "main_duffing.csv",
        json_path=_DUFFING_GT_DIR / "main_duffing_supervised.json",
        json_labels=_DUFFING_JSON_LABELS,
        json_to_python_label=_DUFFING_JSON_TO_PYTHON_LABEL,
        print_name="duffing",
        system_name="duffing",
        case_name="case1",
    )


def generate_friction_case1(n: int = 4000) -> None:
    """Generate baseline ground truth for friction (n=4000)."""
    _export_baseline_ground_truth(
        setup_function=setup_friction_system,
        n=n,
        csv_path=_FRICTION_GT_DIR / "ground_truths" / "main" / "main_friction.csv",
        json_path=_FRICTION_GT_DIR / "main_friction_case1.json",
        json_labels=_PENDULUM_LABELS,
        json_to_python_label={label: label for label in _PENDULUM_LABELS},
        print_name="friction",
        system_name="friction",
        case_name="case1",
    )


def generate_friction_v_study(n: int = 2000) -> None:
    """Generate v_d sweep ground truth for friction (n=2000 per point)."""
    _export_sweep_ground_truth(
        setup_function=setup_friction_system,
        parameter_name='ode_system.params["v_d"]',
        parameter_values=FRICTION_V_D_VALUES,
        n=n,
        csv_dir=_FRICTION_GT_DIR / "ground_truths" / "vStudy",
        json_path=_FRICTION_GT_DIR / "main_friction_v_study.json",
        json_labels=_PENDULUM_LABELS,
        json_to_python_label={label: label for label in _PENDULUM_LABELS},
        print_name="friction",
        system_name="friction",
        case_name="case2",
    )


def generate_lorenz_baseline(n: int = 4000) -> None:
    """Generate baseline ground truth for Lorenz (n=4000)."""
    _export_baseline_ground_truth(
        setup_function=setup_lorenz_system,
        n=n,
        csv_path=_LORENZ_GT_DIR / "ground_truths" / "main" / "main_lorenz.csv",
        json_path=_LORENZ_GT_DIR / "main_lorenz.json",
        json_labels=_LORENZ_JSON_LABELS,
        json_to_python_label=_LORENZ_JSON_TO_PYTHON_LABEL,
        print_name="lorenz",
        system_name="lorenz",
        case_name="case1",
    )


def generate_lorenz_sigma_study(n: int = 2000) -> None:
    """Generate Lorenz sigma sweep ground truth (n=2000 per point)."""
    _export_sweep_ground_truth(
        setup_function=setup_lorenz_system,
        parameter_name='ode_system.params["sigma"]',
        parameter_values=LORENZ_SIGMA_VALUES,
        n=n,
        csv_dir=_LORENZ_GT_DIR / "ground_truths" / "sigmaStudy",
        json_path=_LORENZ_GT_DIR / "main_lorenz_sigma_study.json",
        json_labels=_LORENZ_JSON_LABELS,
        json_to_python_label=_LORENZ_JSON_TO_PYTHON_LABEL,
        print_name="lorenz",
        system_name="lorenz",
        case_name="case2",
    )


def generate_lorenz_hyperparameter_n() -> None:
    """Generate Lorenz N sweep ground truth (n varies per point)."""
    _export_sweep_ground_truth(
        setup_function=setup_lorenz_system,
        parameter_name="n",
        parameter_values=LORENZ_HYPERPARAMETER_N_VALUES,
        n=None,
        csv_dir=_LORENZ_GT_DIR / "ground_truths" / "hyperpN",
        json_path=_LORENZ_GT_DIR / "main_lorenz_hyperparameters.json",
        json_labels=_LORENZ_JSON_LABELS,
        json_to_python_label=_LORENZ_JSON_TO_PYTHON_LABEL,
        print_name="lorenz",
        system_name="lorenz",
        case_name="case4",
    )


def generate_lorenz_hyperparameter_rtol(n: int = 2000) -> None:
    """Generate Lorenz solver rtol sweep ground truth (n=2000 per point)."""
    _export_sweep_ground_truth(
        setup_function=setup_lorenz_system,
        parameter_name="solver.rtol",
        parameter_values=LORENZ_RTOL_VALUES,
        n=n,
        csv_dir=_LORENZ_GT_DIR / "ground_truths" / "hyperpTol",
        json_path=_LORENZ_GT_DIR / "main_lorenz_hyperpTol.json",
        json_labels=_LORENZ_JSON_LABELS,
        json_to_python_label=_LORENZ_JSON_TO_PYTHON_LABEL,
        print_name="lorenz",
        system_name="lorenz",
        case_name="case3",
    )


def generate_all_ground_truths() -> None:
    """Generate all integration ground truth artifacts."""
    generate_case1()
    generate_case2()
    generate_hyperparameters()
    generate_duffing_baselines()
    generate_friction_case1()
    generate_friction_v_study()
    generate_lorenz_baseline()
    generate_lorenz_sigma_study()
    generate_lorenz_hyperparameter_n()
    generate_lorenz_hyperparameter_rtol()


if __name__ == "__main__":
    generate_all_ground_truths()
