#!/usr/bin/env bash
# Quick reference for common commands

echo "🚀 pyBasin Quick Reference"
echo "=========================="
echo ""
echo "📦 Package Management:"
echo "  uv venv                      # Create virtual environment"
echo "  uv pip install -e .          # Install package"
echo "  uv pip install -e '.[dev]'   # Install with dev tools"
echo "  uv pip install -e '.[all]'   # Install everything"
echo ""
echo "🧪 Testing:"
echo "  pytest                       # Run all tests"
echo "  pytest tests/integration/    # Run integration tests only"
echo "  pytest --cov=src/pybasin     # Run with coverage"
echo "  pytest -v -s                 # Verbose output"
echo ""
echo "📖 Documentation:"
echo "  mkdocs serve                 # Preview docs locally"
echo "  mkdocs build                 # Build static docs"
echo ""
echo "🔬 Case Studies:"
echo "  uv run python case_studies/duffing_oscillator/main_supervised.py"
echo "  ./scripts/run_all_case_studies.sh   # Run all"
echo ""
echo "🛠️  Development:"
echo "  black src/ tests/            # Format code"
echo "  ruff check src/ tests/       # Lint code"
echo "  mypy src/                    # Type check"
echo ""
echo "✅ Verification:"
echo "  uv run python scripts/verify_migration.py"
echo ""
