/* Auto-generated by sympy_ode.py — do not edit manually. */
#include <math.h>
#include <stddef.h>

typedef struct {
    double alpha;
    double T;
    double K;
} Params;

void ode_func(double t, const double *y, double *dydt,
              const void *params_ptr, size_t dim)
{
    (void)t;
    (void)dim;
    const Params *p = (const Params *)params_ptr;
    double theta = y[0];
    double dtheta = y[1];
    double alpha = p->alpha;
    double T = p->T;
    double K = p->K;
    dydt[0] = dtheta;
    dydt[1] = -K*sin(theta) + T - alpha*dtheta;
}

size_t ode_dim(void)
{
    return 2;
}

size_t ode_param_size(void)
{
    return sizeof(Params);
}
